import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/components/header/page'
import SidebarLeft from '@/components/sidebar-left/page'
import SidebarRight from '@/components/sidebar-right/page'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Fotobook',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>

      </head>
      <body className={`${inter.className} text-white`}>
        <Header theme='dark' />
        <div className='container'>
          <SidebarLeft/>
          <div className='content'>
            {children}
          </div>
          <SidebarRight/>
        </div>
          
      </body>
    </html>
  )
}
